version: '2'

services:
 updated3dprinter:
    image: updated3dprinter:latest
    container_name: updated3dprinter
    restart: always
    ports:
      - 8085:3000
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=3dprinter.oskarolsson.com
      - LETSENCRYPT_HOST=3dprinter.oskarolsson.com
    volumes: 
      - /mnt/sda1/shared/octoprint/octoprint/timelapse:/public/timelapses
    networks:
      - nginx-network


networks:
  nginx-network:
    external: true