version: '2'

services:
  3dprinter-flask-server:
    image: flask-server-image
    name: 3dprinter-flask-server
    restart: always
    ports:
      - 8084:80
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=3dprinter.oskarolsson.com
      - LETSENCRYPT_HOST=3dprinter.oskarolsson.com
 
    networks:
      - nginx-network


networks:
  nginx-network:
    external: true
