version: '2'

services:
 updated3dprinter:
    image: updated3dprinter:latest
    container_name: updated3dprinter
    restart: always
    ports:
      - 8085:3000
    expose:
      - 3000
    environment:
      - PORT=3000
      - OCTOPRINT_APIKEY=BD86451B85D3458FA21FA8291188D4B0
      - OCTOPRINT_IP=127.0.0.1
      - OCTOPRINT_PORT=8081
      - VIRTUAL_HOST=3dprinter.oskarolsson.com
      - LETSENCRYPT_HOST=3dprinter.oskarolsson.com
    volumes:
      - /mnt/sda1/shared/3dprinterWeb:/usr/src/app
      - /mnt/sda1/shared/octoprint/octoprint/timelapse:/files/timelapses
    networks:
      - nginx-network


networks:
  nginx-network:
    external: true